### ISSUE TITLE
[sqflite_ffi] Error: The getter 'config' isn't defined for the class 'CommonDatabase'.

### ISSUE THREAD

**Issue by dev-yakuza** [tekartik/sqflite#1064]
First, thanks for making such a great package.

I have an app to use `sqflite` and I use `sqflite_ffi` for the test.

## Problem

After I updated `sqflite_common_ffi` from `2.3.0+2` to `2.3.0+4`, I got the error like the following. (The `2.3.0+3` version is fine)

```
00:04 +0: loading /test/controller/review_controller_test.dart                                                                                                           ../../.pub-cache/hosted/pub.dev/sqflite_common_ffi-2.3.0+4/lib/src/sqflite_ffi_impl.dart:192:16: Error: The getter 'config' isn't defined for the class 'CommonDatabase'.
 - 'CommonDatabase' is from 'package:sqlite3/src/database.dart' ('../../.pub-cache/hosted/pub.dev/sqlite3-1.11.2/lib/src/database.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'config'.
        _ffiDb.config.setIntConfig(sqliteDbConfigDefensive, 0);
```

## Environment

The following is the `flutter doctor` result.

```
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.1.1 23B81 darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.2)
[✓] Connected device (2 available)
[✓] Network resources
```

I use the `2.3.0` version of `sqflite`.

## Code

The test code is like the following.

```dart
late Database db;

void main() {
  final testDBPath = join('assets', 'review_screen_controller_test.db');

  setUp(() async {
    File(join('assets', 'test.db')).copySync(testDBPath);
    db = await databaseFactoryFfi.openDatabase(join('../../../', testDBPath));

    ReviewController.removeController();
  });
```

And I tried to add `sqflite fInit();`, but the error still occurs.

**Comment by alextekartik** [comment]
Thanks for the report. Your sqflite3 transitive dependency seems out of date (1.11.2). The weird thing is that 2.3.0+4 has a dependency on sqlite3 >=2.1.0. Can you try to pub upgrade/clean or make sure there is no dependency (or overrides) preventing sqlite3 from upgrading ?

**Comment by dev-yakuza** [comment]
@alextekartik 

Thanks for quick reply.

I searched `sqlite3` in the `pubspec.lock` file and I found the version is `1.11.2`.

```
  sqlite3:
    dependency: transitive
    description:
      name: sqlite3
      sha256: "281b672749af2edf259fc801f0fcba092257425bcd32a0ce1c8237130bc934c7"
      url: "https://pub.dev"
    source: hosted
    version: "1.11.2"
```

So, I deleted the `pubspec.lock` file and reinstall it.

After than, the error is gone.

```
```

**Comment by dev-yakuza** [comment]
@alextekartik 

Thanks for quick reply.

I searched `sqlite3` in the `pubspec.lock` file and I found the version is `1.11.2`.

```
  sqlite3:
    dependency: transitive
    description:
      name: sqlite3
      sha256: "281b672749af2edf259fc801f0fcba092257425bcd32a0ce1c8237130bc934c7"
      url: "https://pub.dev"
    source: hosted
    version: "1.11.2"
```

So, I deleted the `pubspec.lock` file and reinstall it.

After than, the error is gone. And the `sqlite3` version became `2.1.0`.

```
  sqlite3:
    dependency: transitive
    description:
      name: sqlite3
      sha256: db65233e6b99e99b2548932f55a987961bc06d82a31a0665451fa0b4fff4c3fb
      url: "https://pub.dev"
    source: hosted
    version: "2.1.0"
```

Thanks for your help. I will close the issue.
