### ISSUE TITLE
Failed to load dynamic library 'libsqlite3.so'

### ISSUE THREAD

**Issue by thiagocarvalhodev** [tekartik/sqflite#1135]
Our Github Actions started to fail to run the tests. Last week was working, but now it doesn't. 
The issue:
`Invalid argument(s): Failed to load dynamic library 'libsqlite3.so': libsqlite3.so: cannot open shared object file: No such file or directory`

This only happens using the ubuntu-latest on Github actions:  `Ubuntu 24.04.1 LTS`

Downgrading to `ubuntu-22.04.5` fixes the issue.

More info:

```yaml
  sqflite:
    dependency: transitive
    description:
      name: sqflite
      sha256: "5ce2e1a15e822c3b4bfb5400455775e421da7098eed8adc8f26298ada7c9308c"
      url: "https://pub.dev"
    source: hosted
    version: "2.3.3"
  sqflite_common:
    dependency: transitive
    description:
      name: sqflite_common
      sha256: "3da423ce7baf868be70e2c0976c28a1bb2f73644268b7ffa7d2e08eab71f16a4"
      url: "https://pub.dev"
    source: hosted
    version: "2.5.4"
  sqlite3:
    dependency: transitive
    description:
      name: sqlite3
      sha256: "1abbeb84bf2b1a10e5e1138c913123c8aa9d83cd64e5f9a0dd847b3c83063202"
      url: "https://pub.dev"
    source: hosted
    version: "2.4.2"
  sqlite3_flutter_libs:
    dependency: "direct main"
    description:
      name: sqlite3_flutter_libs
      sha256: d6c31c8511c441d1f12f20b607343df1afe4eddf24a1cf85021677c8eea26060
      url: "https://pub.dev"
    source: hosted
    version: "0.5.20"
 ```
