### ISSUE TITLE
sample opening_asset_db.md not working

### ISSUE THREAD

**Issue by luigikitten** [tekartik/sqflite#205]
Hi, 
    newbie here :) I have tried the sample in https://github.com/tekartik/sqflite/blob/master/sqflite/doc/opening_asset_db.md but it stays stuck in:

print("Now copy...");
await new File(path).writeAsBytes(bytes);
print("Now copy... DONE");

i.e. after few minutes I don't see the "DONE" in logs.
Is there anything obvious I may have missed? I have tried also to add WRITE_EXTERNAL_STORAGE permissions (via Android xml + simple_permission) with no luck

Thanks!!!

details:
flutter --version
Flutter 1.5.4-hotfix.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (6 days ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

```
dependencies:
  flutter:
    sdk: flutter
  # sqflite:
  #   git: ## no difference
  #     url: git://github.com/tekartik/sqflite
  #     path: sqflite
  sqflite: ^1.1.5
  path_provider: ^0.4.1
  simple_permissions: ^0.1.9
```

path it tries to write to:
```
/data/user/0/com.example.sqlitedemo/databases/demo_asset_example.db
```

Running on Android 6.0.1

**Comment by alextekartik** [comment]
I would not assume that it hangs, maybe it simply throws an exception. One common issue is when the parent directory does not exist. You can try to make sure the directory exists. Also add the option `flush: true` when calling `writeAsBytes`.

```dart
// Make sure the parent directory exists
try {
  await Directory(dirname(path)).create(recursive: true);
} catch (_) {}
    
// Copy from asset
ByteData data = await rootBundle.load(join("assets", "example.db"));
List<int> bytes =
  data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
  
// Write and flush the bytes written
await File(path).writeAsBytes(bytes, flush: true);
```

I have updated the documentation

**Comment by mustofa-id** [comment]
> I would not assume that it hangs, maybe it simply throws an exception. One common issue is when the parent directory does not exist. You can try to make sure the directory exists. Also add the option `flush: true` when calling `writeAsBytes`.
> 
> ```dart
> // Make sure the parent directory exists
> try {
>   await Directory(dirname(path)).create(recursive: true);
> } catch (_) {}
>     
> // Copy from asset
> ByteData data = await rootBundle.load(join("assets", "example.db"));
> List<int> bytes =
>   data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
>   
> // Write and flush the bytes written
> await File(path).writeAsBytes(bytes, flush: true);
> ```
> 
> I have updated the documentation

I followed this documentation exactly but getting error `(1) no such table: <my_table_name>`.
I checked database file in my rooted Android, the database file is exists and also the table I queried.
I'm sure I've checked my code regularly.

I tested on Android Pie (real device and emulator)

**pubspec.yaml**
```
# ...
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
# ...
  sqflite: ^1.1.5

flutter:
# ...
  assets:
    - assets/my.db
```
