### ISSUE TITLE
MissingPluginException and getDatabasesPath error in Linux when using cached_network_image

### ISSUE THREAD

**Issue by fmatosqg** [tekartik/sqflite#470]
When using package `cached_network_image` I find this error:
  Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)

even though I had manually run `apt install sqlite3 libsqlite3-dev`   with result 
> 0 to upgrade, 0 to newly install, 0 to remove and 9 not to upgrade.

and I can run the test app with only a couple of errors.
```
cd sqflite_test_app/
> flutter run -d linux
```

I tried finding out how to run `getDatabasesPath` with `sqflite_test_app` or any other test, but so far I had no luck. I'd appreciate pointers in this sense.

My `main.dart`
```
. . .
import 'package:sqflite_common_ffi/src/mixin/handler_mixin.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';

void main() {
  setupGetItFactory();
  if (Platform.isWindows || Platform.isLinux) {
    sqfliteFfiInit();
  }
  runApp(MyApp());
}
. . .
```

My pubspec dependencies:
```

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  path_provider: ^1.6.11

  flutter_svg: ^0.18.0
  cached_network_image: ^2.2.0+1 # doesn't work with desktop
  

  http: ^0.12.0
  get_it: ^1.0.3
   
dependency_overrides:
  sqflite:
    path: /home/fabiomint/code/flutter/sample/sqflite/sqflite
  sqflite_common:
    path: /home/fabiomint/code/flutter/sample/sqflite/sqflite_common
  sqflite_common_ffi:
    path: /home/fabiomint/code/flutter/sample/sqflite/sqflite_common_ffi

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi:  
```

more env info:
```
>  flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.20.0-2.0.pre, on Linux, locale en_AU.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.0)
[✓] Android Studio (version 3.6)
[✓] Android Studio (version 4.1)
[!] IntelliJ IDEA Community Edition (version 2019.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (4 available)

! Doctor found issues in 1 category.
```

```
System:    Host: fabio-mint-5520 Kernel: 5.3.0-46-generic x86_64 bits: 64 Desktop: Cinnamon 4.4.8 
           Distro: Linux Mint 19.3 Tricia 
```
