### ISSUE TITLE
Execution failed for task ':sqflite:createFullJarDebug'.

### ISSUE THREAD

**Issue by fhasheminasab** [tekartik/sqflite#519]
Ran into this error after upgrading flutter:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sqflite:createFullJarDebug'.
> java.nio.file.NoSuchFileException: C:\Users\fayem\AndroidStudioProjects\myapp\build\sqflite\intermediates\library_java_res\debug\res.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**pubspec.yaml**

```
name: myapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.3
  adobe_xd: ^1.0.0+1
  path: ^1.6.2
  sqflite: ^1.3.1+1
  flutter_blue: ^0.7.2

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
```

other detail:
