### ISSUE TITLE
Linux snap and sqlite for stable snap release

### ISSUE THREAD

**Issue by hotlittlewhitedog** [tekartik/sqflite#712]
Hi all, 

I have read https://github.com/tekartik/sqflite/issues/502 but it's does not help me for stable release.  

I used sqflite_common_ffi (for linux) and sqflite (for ios, mac, android) in works fine out of the box but with snap something is probably missing to create or reach the sqlite database when I install my snap.   

Here is my snap: 

```
name: bible-multi-the-life
version: 1.13d.0
summary: Bible multi languages free offline KJV, Segond, Diodati, Reina Valera, Almeida
description: Bible multi languages completely in English, French, Italian, Spanish, Portuguese. The Life is a powerful study tool to learn the Word of God. For Android, iPhone, iPad, Big Sur, Mac and Linux :)
type: app
icon: snap/gui/thelifelogo.png
license: GPL-3.0
confinement: strict
base: core18
grade: stable
apps:
  bible-multi-the-life:
    command: bible_multi_the_life
    extensions: [flutter-stable]
    plugs: [home]
parts:
  bible-multi-the-life:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    stage-packages: [libsqlite3-dev]
```
My snap page is here: https://snapcraft.io/bible-multi-the-life  

Can someone help me?   

Thanks a lot,
