### ISSUE TITLE
【build error】 imported error 

### ISSUE THREAD

**Issue by qinchong1988** [tekartik/sqflite#995]
Error: 'getDatabasesPath' is imported from both 'package:sqflite/sqflite.dart' and 'package:sqflite_common/sqflite.dart'.

sqflite:
    dependency: transitive
    description:
      name: sqflite
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0+4"
sqflite_common:
  dependency: transitive
  description:
    name: sqflite_common
    url: "https://pub.dartlang.org/"
  source: hosted
  version: "2.4.4"
sqflite_common_ffi:
  dependency: transitive
  description:
    name: sqflite_common_ffi
    url: "https://pub.dartlang.org/"
  source: hosted
  version: "2.2.4"

**Comment by alextekartik** [comment]
Yes sorry I don't know how to set an upper limit of a previously published package. And sorry I put both an Android project upgrade and some declaration move. You can use the following overrides:
```
dependency_overrides:
  sqflite: '<=2.2.7'
  sqflite_common: '<=2.4.4'
  sqflite_common_ffi: '<=2.2.4'
```
